# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
    ]
